// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyADnzJbYD_VmjlDVYKo6uiL9e190Z1ZW5U',
    appId: '1:27184708519:web:535bd7e69dd3350d1c1482',
    messagingSenderId: '27184708519',
    projectId: 'fir-flutter-codelab-815dd',
    authDomain: 'fir-flutter-codelab-815dd.firebaseapp.com',
    storageBucket: 'fir-flutter-codelab-815dd.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBEMhAoEQu4KPfa76rtHNm49uj4NXIaGYc',
    appId: '1:27184708519:android:f3de2e8d713099cd1c1482',
    messagingSenderId: '27184708519',
    projectId: 'fir-flutter-codelab-815dd',
    storageBucket: 'fir-flutter-codelab-815dd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyASIzL4mgYOjzI-syBDZN_nr-0imz3ycro',
    appId: '1:27184708519:ios:14d91ef3f23046ea1c1482',
    messagingSenderId: '27184708519',
    projectId: 'fir-flutter-codelab-815dd',
    storageBucket: 'fir-flutter-codelab-815dd.appspot.com',
    iosBundleId: 'com.example.gtkFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyASIzL4mgYOjzI-syBDZN_nr-0imz3ycro',
    appId: '1:27184708519:ios:14d91ef3f23046ea1c1482',
    messagingSenderId: '27184708519',
    projectId: 'fir-flutter-codelab-815dd',
    storageBucket: 'fir-flutter-codelab-815dd.appspot.com',
    iosBundleId: 'com.example.gtkFlutter',
  );
}
